spring:
  application:
    name: charge-demo

mqtt:
  host: tcp://localhost:18084
  clientId: mqtt_idea123
  options:
    username:
    password:
#   false表示服务端会保留客户端的连接记录
#   客户端重新连接之后能获取到服务器在客户端断开连接期间推送的消息
    clean_session: false
  topic: test
