server:
  port: 8686
spring:
  application:
    name: charge-mqtt-client

mqtt:
  host: tcp://localhost:18084
  clientId: charge_mqtt_client
  # 发送消息的主题
  topics: charge/cmd,charge/resp,mqtt/willMsg,charge/status
  options:
#    username:
#    password:
#   false表示服务端会保留客户端的连接记录
#   客户端重新连接之后能获取到服务器在客户端断开连接期间推送的消息
    clean_session: false

